[package]
name = "uniffi-bindgen"
version = "0.28.0"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
homepage.workspace = true

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true