name: "Setup"
description: "Setup js environment and dependencies"
runs:
  using: "composite"

  steps:
    - name: Use Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
      with:
        node-version: 20.18.0
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Get better-sqlite3 cached location
      shell: bash
      run: |
        echo "better_sqlite3_path=$(node buildSrc/getNativeCacheLocation.js better-sqlite3)" >> $GITHUB_ENV
    - name: try to use cached better-sqlite3
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 #v4.2.0
      with:
        path: ${{ env.better_sqlite3_path }}
        key: ${{ env.better_sqlite3_path }}
    - name: install packages
      shell: bash
      run: npm ci